version: "3"

services:
  etherpad:
    image: etherpad/etherpad:2.0.3
    build:
      # context: .
      args:
        # - ETHERPAD_PLUGINS="ep_adminpads3 ep_author_hover ep_brightcolorpicker ep_pad_activity_nofication_in_title ep_post_data ep_prompt_for_name ep_sync_status"
        - ETHERPAD_PLUGINS="ep_author_hover"
        # - ETHERPAD_LOCAL_PLUGINS="ep_simple_urls"
        - SETTINGS=./settings.json
    restart: always
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=etherpad
      - DB_USER=etherpad
      - DB_PASS=secretpassword
      - ADMIN_PASSWORD=secretpassword
      - IMPORT_EXPORT_MAX_REQ_PER_IP=1000
    ports:
      - "9001:9001"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=etherpad
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=etherpad
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
