version: "3"

services:
  etherpad:
    build: .
    restart: always
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=etherpad
      - DB_USER=etherpad
      - DB_PASS=secretpassword
      - ADMIN_PASSWORD=secretpassword
      - IMPORT_EXPORT_MAX_REQ_PER_IP=1000
    ports:
      - "9001:9001"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=etherpad
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=etherpad
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
