services:
  - type: web
    name: web
    runtime: docker
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: db
          property: database
      - key: DB_USER
        fromDatabase:
          name: db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: db
          property: password
databases:
  - name: db
    plan: standard
