name: CI
on:
  push:
env:
  PNPM_VERSION: 9
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ep_simple_urls
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
      - run: pnpm install
      - run: pnpm test
