name: Deploy
on:
  push:
    # branches:
    #   - main
    #   - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init --recursive
      - run: ./docker-build.sh
